kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cvad-power-management
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - kubevirt.io
    resources:
      - virtualmachine
      - virtualmachines
      - virtualmachineinstance
      - virtualmachineinstances
  - verbs:
      - watch
      - list
      - get
    apiGroups:
      - k8s.cni.cncf.io
    resources:
      - network-attachment-definition
      - network-attachment-definitions
  - verbs:
      - update
    apiGroups:
      - subresources.kubevirt.io
    resources:
      - virtualmachines/start
      - virtualmachines/stop
      - virtualmachines/restart
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - ''
    resources:
      - configmaps
  - verbs:
      - get
      - list
    apiGroups:
      - ''
    resources:
      - secrets